### ISSUE TITLE
GetObject not working as expected

### ISSUE THREAD

**Issue by k0r8i** [aerospike/aerospike-client-go#130]
Hi there!
I think I might have encountered a problem when reading data using GetObject.
Let's say I do have a simple struct
`type Pics struct{
 PictureNames []string 'as:"b"'
}`
that I use to get my data off the set.
`b := new(Pics)
if err := client.GetObject(nil, key, b); err != nil{
 panic(err)
}`
I started digging into aerospike's go library and encountered that each object's tags are cached using cacheObjectTags(obj reflect.Value) whereas pointer is somehow dereferenced when storing type in SyncMap (reflect.Indirect(obj)). All looks fine, my as-value "b" is stored in SyncMap[<db.Pics Value>].
GetObject then tries to get object's fields using
`binNames := objectMappings.getFields(rval)`
with getFields looking for  [<*db.Pics Value>] in SyncMap, pointer is not dereferenced here.
Lookup leads to an empty binNames slice.
Shouldn't pointer be dereferenced in getFields-method as well to not cause any empty slices?

Cheers,
Korbi

**Comment by khaf** [comment]
Thanks for your report. Will take care of it ASAP.

**Comment by k0r8i** [comment]
Awesome - thanks for your quick reply!

**Comment by khaf** [comment]
Fix pushed to the master. Please let me know if it resolves your issue.

**Comment by k0r8i** [comment]
Nope, still having the same issues here:
`(sm *SyncMap) setMapping(obj reflect.Value, mapping map[string]string, fields, ttl, gen []string)`
is using [db.Pics] as objType.
`func (sm *SyncMap) getFields(obj reflect.Value) []string`
is trying to read  [*db.Pics].

**Comment by khaf** [comment]
Can you provide a snippet that shows that a struct is being saved and fails to read properly?

**Comment by k0r8i** [comment]
Meap, my fault - it's working now as expected. Thanks for your effort!

**Comment by khaf** [comment]
Cheers.
