### ISSUE TITLE
ExecuteUDF OnComplete() returns EOF

### ISSUE THREAD

**Issue by alicebob** [aerospike/aerospike-client-go#185]
I run a batch job like this:

```
    res, err := c.ExecuteUDF(
        nil,
        as.NewStatement("my_ns", ""),
        "my_module",
        "my_function",
        as.NewValue(my_first_value),
        as.NewValue(my_second_value),
    )
    if err != nil {
        return err
    }
    return <-res.OnComplete()
```

This works, the job runs successfully according to AMC, but it returns an `EOF` error. The job takes about 12 minutes to finish. In a previous version of the Go client the error wasn't there. This is with the latest Go client, and server 3.10.0.3. Any ideas?

**Comment by khaf** [comment]
I'm looking into this. Will update this ticket soon.

**Comment by khaf** [comment]
I still haven't been to reproduce this issue. Has it been happening consistently?

**Comment by alicebob** [comment]
Thanks for the help. I'll see if I can bisect it down a bit, but that will take me a while.

tbc!

**Comment by khaf** [comment]
Did you manage to find the issue? IS it still happening?

**Comment by alicebob** [comment]
Updated the aerospike daemon to the latest version and the client and it still happens :/
I tried a bisect once and didn't get far (takes work to get the old version to compile again). Fifuring this out is still on my list, but since it seems to work just fine otherwise it's very low on that list...

**Comment by alicebob** [comment]
I get it every time with this client:

```
package main

import (
    "log"

    as "github.com/aerospike/aerospike-client-go"
)

func main() {
    cl, err := as.NewClient("10.32.100.33", 3000)
    if err != nil {
        log.Fatal(err)
    }

    res, err := cl.ExecuteUDF(
        nil,
        as.NewStatement("rz", ""),
        "debugdemographics",
        "noopcalc",
    )
    if err != nil {
        log.Fatalf("err: %s\n", err)
    }
    if err := <-res.OnComplete(); err != nil {
        log.Fatalf("OnComplete err: %s\n", err)
    }
}
```

The .lua code:
```
function noopcalc(r)
    if not aerospike:exists(r) then
        return "does not exist"
    end
end
```

Three servers, all 3.12.1.1.

I don't get the error if I test against a single localhost machine.

**Comment by alicebob** [comment]
Changing ```as.NewStatement("rz", ""),``` to ```as.NewStatement("rz", "foo"),``` makes the error go away, but also no records match.

**Comment by khaf** [comment]
Still can't reproduce this error. How many records do you have in your set?

Do you get the same error if you use the `aql`?

**Comment by alicebob** [comment]
A few hundered million records.

Could you give me the exact `aql` command?

**Comment by alicebob** [comment]
```aql> EXECUTE debugdemographics.noopcalc() on rz
OK, scan job (7384188128896062020) created.
```

How can I do the equivalent of 'OnComplete()` ?

**Comment by khaf** [comment]
unfortunately it's only fire and forget. I guess what's happening is that you're getting a one-off `EOF` from the server, and the client returns that error instead of retrying the command.

I'll see what I can do.

**Comment by khaf** [comment]
unfortunately it's only fire and forget. I guess what's happening is that you're getting a one-off `EOF` from the server, and the client returns that error instead of retrying the command.

I'll see what I can do.

**Comment by alicebob** [comment]
Is there anything I can look for? Maybe something in the server logs?

**Comment by alicebob** [comment]
I saw you added a retry option. Seems like that actually solved it! I'll run the command a few more times, to be sure.

**Comment by khaf** [comment]
I thought I let you know about that! Yes I believe should be fixed now.

**Comment by alicebob** [comment]
It is fixed, but disabling the retry doesn't make it break again. I'll keep looking for a bit, I would like to know what really caused it. But considered it fixed anyway, thanks!

**Comment by khaf** [comment]
Thanks. Let me know in case you come up with something.

**Comment by alicebob** [comment]
The retry commit (4a995bc) indeed is the commit whic fixes it. Looking at the code and the output while running it I think this is what happened:

OnComplete() polls all nodes once a second until all nodes return 'done' for the task. For this it loops over the nodes, and if a single node is not done yet it stops checking. The order in which it checks the nodes is always the same, though. That means that it keeps checking the same node until that node is done (which takes ~30 minutes). Only when that first node is done it'll check the second node, and so on. That means the connection to the second node stays idle for 30 minutes, and apparently is closed by that time, or maybe it's never even made yet. Either way, the cause is that for a long time only a single node is checked.

If this hypothesis is correct the retry fix seems perfectly reasonable to me.

**Comment by khaf** [comment]
The issue was that the process would error out if the info call to a node timed out. By retrying a few times before returning an error, this issue was fixed. No connections to nodes are made specifically for this process, and the normal tend connection is used.

**Comment by alicebob** [comment]
That still doesn't explain why it only happened at the end of a run. It never happens after just a few minutes. This runs from a cron, so there is nothing else which uses the connections, so they will stay idle for a while.

**Comment by khaf** [comment]
Both the server and the client reap idle connections, and if the connection was dropped from the server side, the client wouldn't know and would error out on poll. Without a retry, the task would return that error instead of trying an fresh connection.

**Comment by alicebob** [comment]
I agree, but I'm happy to have figured out why it happened only late in the script. Thanks for the help!
